name: lunch_recipe
description: Flutter App for Lunch Recipes Suggestion

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  chopper: ^3.0.3
  cupertino_icons: ^0.1.2
  dartz: ^0.9.1
  data_connection_checker: ^0.3.4
  flutter_mobx: ^1.1.0
  freezed: ^0.11.2
  get_it: ^3.1.0
  injectable: ^0.4.0
  intl: ^0.16.1
  json_serializable: ^3.3.0
  mobx: ^1.1.1
  mobx_codegen: ^1.0.3
  provider: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  chopper_generator: ^3.0.3
  injectable_generator: ^0.4.0
  mockito: ^4.1.1
  flutter_coverage_badge: ^0.0.1+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
